# Generated by Django 2.2.4 on 2019-08-22 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0002_list_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
