# Generated by Django 2.2.4 on 2019-08-22 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0003_auto_20190823_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
